db:
  image: orchardup/mysql
  environment:
    - MYSQL_DATABASE=wordpress

web:
  image: orchardup/php5
  command: ["php", "-S", "0.0.0.0:8000", "-t", "/code"]
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - /vagrant/wordpress/wordpress:/code
