# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "talk2docker"

  config.vm.box = "ailispaw/docker-root"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.network :forwarded_port, guest: 8000, host: 8000
end
